### ISSUE TITLE
encrypt, decrypt not same with java output

### ISSUE THREAD

**Issue by chanmratekoko** [xiangdingquan/Aes#2]
Hi, xiangdingquan

When I was testing with Samsung Tab S  Version 6.0.
 1. encrypt, decrypt output result change in every test.
2. Java output cannot decrypt using with JNI.

https://github.com/xiangdingquan/Aes/blob/10cc4b94931fbe41065838309dd940d2f29ccc13/app/src/main/cpp/encrypt.cpp#L70

Could you please check it. And Fix

**Comment by xiangdingquan** [comment]
maybe you can use     abiFilters  "armeabi-v7a"

**Comment by xiangdingquan** [comment]
> Hi, xiangdingquan
> 
> When I was testing with Samsung Tab S Version 6.0.
> 
> 1. encrypt, decrypt output result change in every test.
> 2. Java output cannot decrypt using with JNI.
> 
> https://github.com/xiangdingquan/Aes/blob/10cc4b94931fbe41065838309dd940d2f29ccc13/app/src/main/cpp/encrypt.cpp#L70
> 
> Could you please check it. And Fix

**Comment by xiangdingquan** [comment]
> Hi, xiangdingquan
> 
> When I was testing with Samsung Tab S Version 6.0.
> 
> 1. encrypt, decrypt output result change in every test.
> 2. Java output cannot decrypt using with JNI.
> 
> https://github.com/xiangdingquan/Aes/blob/10cc4b94931fbe41065838309dd940d2f29ccc13/app/src/main/cpp/encrypt.cpp#L70
> 
> Could you please check it. And Fix

Please check that your java version of base64 code is used in Base64.URL_SAFE mode!

**Comment by chanmratekoko** [comment]
>Please check that your java version of base64 code is used in Base64.URL_SAFE mode!

@xiangdingquan 

I already used Base64.URL_SAFE  mode. 

JNI encrypt, decrypt output result change in every test.
For java is not change.

**Comment by xiangdingquan** [comment]
> > Please check that your java version of base64 code is used in Base64.URL_SAFE mode!
> 
> @xiangdingquan
> 
> I already used Base64.URL_SAFE mode.
> 
> JNI encrypt, decrypt output result change in every test.
> For java is not change.

show me your code

**Comment by xiangdingquan** [comment]
> > > Please check that your java version of base64 code is used in Base64.URL_SAFE mode!
> > 
> > 
> > @xiangdingquan
> > I already used Base64.URL_SAFE mode.
> > JNI encrypt, decrypt output result change in every test.
> > For java is not change.
> 
> show me your code

Have you tried any other models?

**Comment by chanmratekoko** [comment]
@xiangdingquan 

I tried with this repo is fine. 

https://github.com/wtuadn/JNITool

But It hasn't integrated with java cyto. 
So I can't compare those two result. 

How did you test it? Code posted
